title: CSS Boxframe - Simplyfing CSS Learning
email: cssboxframe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  CSS Boxframe is a set of techniques and practices to easily and systemically
  learn CSS which will eventually help master CSS
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cssboxframe.github.io"
image_base_url: /assets/img

google_analytics: # your google analytics id

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
